// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartSure.PolicyService.Data;

#nullable disable

namespace SmartSure.PolicyService.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    [Migration("20260328154103_AddClaimLimitTracking")]
    partial class AddClaimLimitTracking
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SmartSure.PolicyService.Models.Discount", b =>
                {
                    b.Property<Guid>("DiscountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstTimeOnly")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxDiscountAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Percentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime2");

                    b.HasKey("DiscountId");

                    b.ToTable("Discounts");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.HomeDetail", b =>
                {
                    b.Property<Guid>("HomeDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityFeatures")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("HomeDetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("HomeDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceSubtype", b =>
                {
                    b.Property<Guid>("SubtypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BasePremium")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TypeId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("SubtypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("InsuranceSubtypes");

                    b.HasData(
                        new
                        {
                            SubtypeId = new Guid("11111111-0001-0000-0000-000000000001"),
                            BasePremium = 15000m,
                            Description = "Insurance for Mahindra vehicles",
                            Name = "Mahindra",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0002-0000-0000-000000000002"),
                            BasePremium = 12000m,
                            Description = "Insurance for Maruti Suzuki vehicles",
                            Name = "Maruti Suzuki",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0003-0000-0000-000000000003"),
                            BasePremium = 13000m,
                            Description = "Insurance for Hyundai vehicles",
                            Name = "Hyundai",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0004-0000-0000-000000000004"),
                            BasePremium = 14000m,
                            Description = "Insurance for Honda vehicles",
                            Name = "Honda",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0005-0000-0000-000000000005"),
                            BasePremium = 13500m,
                            Description = "Insurance for Tata vehicles",
                            Name = "Tata Motors",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0006-0000-0000-000000000006"),
                            BasePremium = 16000m,
                            Description = "Insurance for Toyota vehicles",
                            Name = "Toyota",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0007-0000-0000-000000000007"),
                            BasePremium = 14500m,
                            Description = "Insurance for Kia vehicles",
                            Name = "Kia",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0008-0000-0000-000000000008"),
                            BasePremium = 17000m,
                            Description = "Insurance for Volkswagen vehicles",
                            Name = "Volkswagen",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0009-0000-0000-000000000009"),
                            BasePremium = 16500m,
                            Description = "Insurance for Skoda vehicles",
                            Name = "Skoda",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0010-0000-0000-000000000010"),
                            BasePremium = 13000m,
                            Description = "Insurance for Renault vehicles",
                            Name = "Renault",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0011-0000-0000-000000000011"),
                            BasePremium = 14000m,
                            Description = "Insurance for Nissan vehicles",
                            Name = "Nissan",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0012-0000-0000-000000000012"),
                            BasePremium = 15500m,
                            Description = "Insurance for Ford vehicles",
                            Name = "Ford",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0013-0000-0000-000000000013"),
                            BasePremium = 15000m,
                            Description = "Insurance for MG Motor vehicles",
                            Name = "MG Motor",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0014-0000-0000-000000000014"),
                            BasePremium = 18000m,
                            Description = "Insurance for Jeep vehicles",
                            Name = "Jeep",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0015-0000-0000-000000000015"),
                            BasePremium = 25000m,
                            Description = "Insurance for BMW vehicles",
                            Name = "BMW",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0016-0000-0000-000000000016"),
                            BasePremium = 28000m,
                            Description = "Insurance for Mercedes-Benz vehicles",
                            Name = "Mercedes-Benz",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0017-0000-0000-000000000017"),
                            BasePremium = 26000m,
                            Description = "Insurance for Audi vehicles",
                            Name = "Audi",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("11111111-0018-0000-0000-000000000018"),
                            BasePremium = 24000m,
                            Description = "Insurance for Volvo vehicles",
                            Name = "Volvo",
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0001-0000-0000-000000000001"),
                            BasePremium = 8000m,
                            Description = "Insurance for apartments and flats",
                            Name = "Apartment",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0002-0000-0000-000000000002"),
                            BasePremium = 12000m,
                            Description = "Insurance for independent houses",
                            Name = "Independent House",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0003-0000-0000-000000000003"),
                            BasePremium = 18000m,
                            Description = "Insurance for villas and luxury homes",
                            Name = "Villa",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0004-0000-0000-000000000004"),
                            BasePremium = 15000m,
                            Description = "Insurance for bungalows",
                            Name = "Bungalow",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0005-0000-0000-000000000005"),
                            BasePremium = 20000m,
                            Description = "Insurance for penthouses",
                            Name = "Penthouse",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0006-0000-0000-000000000006"),
                            BasePremium = 6000m,
                            Description = "Insurance for studio apartments",
                            Name = "Studio Apartment",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0007-0000-0000-000000000007"),
                            BasePremium = 14000m,
                            Description = "Insurance for duplex homes",
                            Name = "Duplex",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        },
                        new
                        {
                            SubtypeId = new Guid("22222222-0008-0000-0000-000000000008"),
                            BasePremium = 16000m,
                            Description = "Insurance for farmhouses",
                            Name = "Farmhouse",
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222")
                        });
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceType", b =>
                {
                    b.Property<Guid>("TypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("TypeId");

                    b.ToTable("InsuranceTypes");

                    b.HasData(
                        new
                        {
                            TypeId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Description = "Comprehensive vehicle insurance coverage",
                            Name = "Vehicle"
                        },
                        new
                        {
                            TypeId = new Guid("22222222-2222-2222-2222-222222222222"),
                            Description = "Complete home and property insurance",
                            Name = "Home"
                        });
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Payment", b =>
                {
                    b.Property<Guid>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TransactionReference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PaymentId");

                    b.HasIndex("PolicyId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.Property<Guid>("PolicyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ApprovedClaimsCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("InsuredDeclaredValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsTerminated")
                        .HasColumnType("bit");

                    b.Property<string>("NomineeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NomineeRelation")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PremiumAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("SubtypeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("PolicyId");

                    b.HasIndex("SubtypeId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.PolicyDetail", b =>
                {
                    b.Property<Guid>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Exclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Inclusions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TermsAndConditions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DocumentId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("PolicyDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.VehicleDetail", b =>
                {
                    b.Property<Guid>("VehicleDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ChassisNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EngineNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("EstimatedValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ManufactureYear")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("VehicleDetailId");

                    b.HasIndex("PolicyId")
                        .IsUnique();

                    b.ToTable("VehicleDetails");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.HomeDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("HomeDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.HomeDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceSubtype", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.InsuranceType", "Type")
                        .WithMany("Subtypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Type");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Payment", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithMany("Payments")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.InsuranceSubtype", "Subtype")
                        .WithMany()
                        .HasForeignKey("SubtypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Subtype");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.PolicyDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("PolicyDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.PolicyDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.VehicleDetail", b =>
                {
                    b.HasOne("SmartSure.PolicyService.Models.Policy", "Policy")
                        .WithOne("VehicleDetail")
                        .HasForeignKey("SmartSure.PolicyService.Models.VehicleDetail", "PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.InsuranceType", b =>
                {
                    b.Navigation("Subtypes");
                });

            modelBuilder.Entity("SmartSure.PolicyService.Models.Policy", b =>
                {
                    b.Navigation("HomeDetail")
                        .IsRequired();

                    b.Navigation("Payments");

                    b.Navigation("PolicyDetail")
                        .IsRequired();

                    b.Navigation("VehicleDetail")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
