import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router } from '@angular/router';
import { MatCardModule } from '@angular/material/card';
import { MatIconModule } from '@angular/material/icon';
import { MatButtonModule } from '@angular/material/button';
import { MatTableModule } from '@angular/material/table';
import { MatChipsModule } from '@angular/material/chips';
import { NavbarComponent } from '../../../../shared/components/navbar/navbar.component';
import { FooterComponent } from '../../../../shared/components/footer/footer.component';
import { AdminService } from '../../../../services/admin.service';
import { Report } from '../../../../models/admin.models';
import { ToastrService } from 'ngx-toastr';

@Component({
  selector: 'app-report-list',
  standalone: true,
  imports: [
    CommonModule,
    MatCardModule,
    MatIconModule,
    MatButtonModule,
    MatTableModule,
    MatChipsModule,
    NavbarComponent,
    FooterComponent
  ],
  template: `
    <div class="report-list-page">
      <app-navbar></app-navbar>

      <div class="container">
        <div class="page-header">
          <div>
            <h1>Reports</h1>
            <p>View and download system reports</p>
          </div>
          <button mat-raised-button color="primary" (click)="navigateToGenerate()">
            <mat-icon>add</mat-icon>
            Generate New Report
          </button>
        </div>

        <!-- Quick Stats -->
        <div class="stats-grid">
          <mat-card class="stat-card">
            <mat-icon class="stat-icon">description</mat-icon>
            <div class="stat-content">
              <h3>{{ reports.length }}</h3>
              <p>Total Reports</p>
            </div>
          </mat-card>

          <mat-card class="stat-card">
            <mat-icon class="stat-icon">today</mat-icon>
            <div class="stat-content">
              <h3>{{ getTodayReports() }}</h3>
              <p>Generated Today</p>
            </div>
          </mat-card>

          <mat-card class="stat-card">
            <mat-icon class="stat-icon">trending_up</mat-icon>
            <div class="stat-content">
              <h3>{{ getThisMonthReports() }}</h3>
              <p>This Month</p>
            </div>
          </mat-card>
        </div>

        <!-- Reports Table -->
        <mat-card class="reports-card">
          <div class="card-header">
            <h2>All Reports</h2>
            <button mat-raised-button (click)="loadReports()">
              <mat-icon>refresh</mat-icon>
              Refresh
            </button>
          </div>

          <div class="table-container" *ngIf="reports.length > 0">
            <table mat-table [dataSource]="reports" class="reports-table">
              <!-- Report Name Column -->
              <ng-container matColumnDef="name">
                <th mat-header-cell *matHeaderCellDef>Report Name</th>
                <td mat-cell *matCellDef="let report">
                  <div class="report-info">
                    <mat-icon>{{ getReportIcon(report.reportType) }}</mat-icon>
                    <div>
                      <strong>{{ report.reportName || report.title }}</strong>
                      <span class="report-type">{{ report.reportType }}</span>
                    </div>
                  </div>
                </td>
              </ng-container>

              <!-- Period Column -->
              <ng-container matColumnDef="period">
                <th mat-header-cell *matHeaderCellDef>Period</th>
                <td mat-cell *matCellDef="let report">
                  <div class="period">
                    {{ report.startDate | date:'shortDate' }} - {{ report.endDate | date:'shortDate' }}
                  </div>
                </td>
              </ng-container>

              <!-- Generated Column -->
              <ng-container matColumnDef="generated">
                <th mat-header-cell *matHeaderCellDef>Generated</th>
                <td mat-cell *matCellDef="let report">
                  {{ report.generatedAt | date:'medium' }}
                </td>
              </ng-container>

              <!-- Generated By Column -->
              <ng-container matColumnDef="generatedBy">
                <th mat-header-cell *matHeaderCellDef>Generated By</th>
                <td mat-cell *matCellDef="let report">
                  {{ report.generatedBy || 'System' }}
                </td>
              </ng-container>

              <!-- Status Column -->
              <ng-container matColumnDef="status">
                <th mat-header-cell *matHeaderCellDef>Status</th>
                <td mat-cell *matCellDef="let report">
                  <mat-chip [class.ready-chip]="report.status === 'Ready'" 
                            [class.processing-chip]="report.status === 'Processing'">
                    {{ report.status }}
                  </mat-chip>
                </td>
              </ng-container>

              <!-- Actions Column -->
              <ng-container matColumnDef="actions">
                <th mat-header-cell *matHeaderCellDef>Actions</th>
                <td mat-cell *matCellDef="let report">
                  <button mat-icon-button (click)="viewReport(report)" 
                          [disabled]="report.status !== 'Ready'">
                    <mat-icon>visibility</mat-icon>
                  </button>
                  <button mat-icon-button (click)="downloadReport(report)" 
                          [disabled]="report.status !== 'Ready'">
                    <mat-icon>download</mat-icon>
                  </button>
                  <button mat-icon-button (click)="deleteReport(report)" class="danger">
                    <mat-icon>delete</mat-icon>
                  </button>
                </td>
              </ng-container>

              <tr mat-header-row *matHeaderRowDef="displayedColumns"></tr>
              <tr mat-row *matRowDef="let row; columns: displayedColumns;"></tr>
            </table>
          </div>

          <div class="empty-state" *ngIf="reports.length === 0">
            <mat-icon>assessment</mat-icon>
            <h3>No Reports Available</h3>
            <p>Generate your first report to get started</p>
            <button mat-raised-button color="primary" (click)="navigateToGenerate()">
              <mat-icon>add</mat-icon>
              Generate Report
            </button>
          </div>
        </mat-card>
      </div>

      <app-footer></app-footer>
    </div>
  `,
  styles: [`
    .report-list-page {
      min-height: 100vh;
      background: #f5f5f5;
    }

    .container {
      max-width: 1400px;
      margin: 0 auto;
      padding: 20px;
    }

    .page-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      margin-bottom: 30px;
      background: white;
      padding: 30px;
      border-radius: 8px;
    }

    .page-header h1 {
      margin: 0 0 8px 0;
      font-size: 28px;
    }

    .page-header p {
      margin: 0;
      color: #666;
    }

    .stats-grid {
      display: grid;
      grid-template-columns: repeat(auto-fit, minmax(250px, 1fr));
      gap: 20px;
      margin-bottom: 30px;
    }

    .stat-card {
      padding: 24px;
      display: flex;
      align-items: center;
      gap: 20px;
    }

    .stat-icon {
      font-size: 48px;
      width: 48px;
      height: 48px;
      color: #667eea;
    }

    .stat-content h3 {
      margin: 0 0 4px 0;
      font-size: 32px;
      font-weight: 700;
      color: #333;
    }

    .stat-content p {
      margin: 0;
      color: #666;
      font-size: 14px;
    }

    .reports-card {
      padding: 0;
    }

    .card-header {
      display: flex;
      justify-content: space-between;
      align-items: center;
      padding: 20px 24px;
      border-bottom: 1px solid #eee;
    }

    .card-header h2 {
      margin: 0;
      font-size: 20px;
    }

    .table-container {
      overflow-x: auto;
    }

    .reports-table {
      width: 100%;
    }

    .report-info {
      display: flex;
      align-items: center;
      gap: 12px;
    }

    .report-info mat-icon {
      color: #667eea;
    }

    .report-info strong {
      display: block;
      color: #333;
    }

    .report-type {
      display: block;
      font-size: 12px;
      color: #999;
    }

    .period {
      font-size: 14px;
      color: #666;
    }

    mat-chip {
      font-size: 12px;
      min-height: 24px;
    }

    .ready-chip {
      background: #d1fae5;
      color: #065f46;
    }

    .processing-chip {
      background: #fef3c7;
      color: #92400e;
    }

    .empty-state {
      text-align: center;
      padding: 80px 20px;
      color: #999;
    }

    .empty-state mat-icon {
      font-size: 80px;
      width: 80px;
      height: 80px;
      margin-bottom: 16px;
    }

    .empty-state h3 {
      margin: 0 0 8px 0;
      font-size: 20px;
    }

    .empty-state p {
      margin: 0 0 20px 0;
    }

    .danger {
      color: #f44336;
    }

    @media (max-width: 768px) {
      .page-header {
        flex-direction: column;
        align-items: flex-start;
        gap: 16px;
      }

      .page-header button {
        width: 100%;
      }

      .stats-grid {
        grid-template-columns: 1fr;
      }
    }
  `]
})
export class ReportListComponent implements OnInit {
  private router = inject(Router);
  private adminService = inject(AdminService);
  private toastr = inject(ToastrService);

  reports: Report[] = [];
  displayedColumns = ['name', 'period', 'generated', 'generatedBy', 'status', 'actions'];

  ngOnInit(): void {
    this.loadReports();
  }

  loadReports(): void {
    this.adminService.getReports().subscribe({
      next: (reports) => {
        this.reports = reports;
      },
      error: () => {
        this.toastr.error('Failed to load reports');
        // Use mock data for demo
        this.reports = [];
      }
    });
  }

  getTodayReports(): number {
    const today = new Date().toDateString();
    return this.reports.filter(r => new Date(r.generatedAt).toDateString() === today).length;
  }

  getThisMonthReports(): number {
    const now = new Date();
    return this.reports.filter(r => {
      const date = new Date(r.generatedAt);
      return date.getMonth() === now.getMonth() && date.getFullYear() === now.getFullYear();
    }).length;
  }

  getReportIcon(type: string): string {
    const iconMap: { [key: string]: string } = {
      'Policy': 'policy',
      'Claims': 'assignment',
      'Revenue': 'account_balance_wallet',
      'Users': 'people',
      'Performance': 'trending_up'
    };
    return iconMap[type] || 'description';
  }

  navigateToGenerate(): void {
    this.router.navigate(['/admin/reports/generate']);
  }

  viewReport(report: Report): void {
    this.toastr.info(`Viewing report: ${report.reportName || report.title}`);
  }

  downloadReport(report: Report): void {
    this.adminService.downloadReport(report.reportId).subscribe({
      next: (blob) => {
        const url = window.URL.createObjectURL(blob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${report.reportName || report.title}.pdf`;
        link.click();
        window.URL.revokeObjectURL(url);
        this.toastr.success('Report downloaded successfully');
      },
      error: () => {
        this.toastr.error('Failed to download report');
      }
    });
  }

  deleteReport(report: Report): void {
    if (confirm(`Delete report "${report.reportName || report.title}"?`)) {
      this.adminService.deleteReport(report.reportId).subscribe({
        next: () => {
          this.toastr.success('Report deleted successfully');
          this.loadReports();
        },
        error: () => {
          this.toastr.error('Failed to delete report');
        }
      });
    }
  }
}
