// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PolicyService.Data;

#nullable disable

namespace PolicyService.Migrations
{
    [DbContext(typeof(PolicyDbContext))]
    partial class PolicyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PolicyService.Models.InsuranceProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("AdminFee")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("BasePremiumRate")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EligibilityCriteria")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("MaxCoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MaxTermYears")
                        .HasColumnType("int");

                    b.Property<decimal>("MinCoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MinTermYears")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("RequiredDocuments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("InsuranceProducts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            AdminFee = 100m,
                            BasePremiumRate = 1.5m,
                            Category = "Life",
                            CreatedAt = new DateTime(2026, 3, 28, 6, 24, 3, 728, DateTimeKind.Utc).AddTicks(2660),
                            Description = "Comprehensive life coverage for your family's financial security",
                            EligibilityCriteria = "",
                            Features = "[\"Death Benefit\",\"Accidental Death\",\"Critical Illness Cover\"]",
                            IsActive = true,
                            IsDeleted = false,
                            MaxCoverageAmount = 10000000m,
                            MaxTermYears = 30,
                            MinCoverageAmount = 500000m,
                            MinTermYears = 5,
                            Name = "Term Life Insurance",
                            RequiredDocuments = "[\"ID Proof\",\"Address Proof\",\"Medical Reports\"]"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            AdminFee = 200m,
                            BasePremiumRate = 3.5m,
                            Category = "Health",
                            CreatedAt = new DateTime(2026, 3, 28, 6, 24, 3, 728, DateTimeKind.Utc).AddTicks(2688),
                            Description = "Complete health coverage with cashless treatment",
                            EligibilityCriteria = "",
                            Features = "[\"Hospitalization Cover\",\"Pre-existing Diseases\",\"Maternity Cover\"]",
                            IsActive = true,
                            IsDeleted = false,
                            MaxCoverageAmount = 5000000m,
                            MaxTermYears = 10,
                            MinCoverageAmount = 500000m,
                            MinTermYears = 1,
                            Name = "Health Shield",
                            RequiredDocuments = "[\"ID Proof\",\"Medical History\"]"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            AdminFee = 150m,
                            BasePremiumRate = 2.5m,
                            Category = "Auto",
                            CreatedAt = new DateTime(2026, 3, 28, 6, 24, 3, 728, DateTimeKind.Utc).AddTicks(2718),
                            Description = "Comprehensive car insurance with roadside assistance",
                            EligibilityCriteria = "",
                            Features = "[\"Third Party Cover\",\"Own Damage\",\"Roadside Assistance\"]",
                            IsActive = true,
                            IsDeleted = false,
                            MaxCoverageAmount = 5000000m,
                            MaxTermYears = 5,
                            MinCoverageAmount = 100000m,
                            MinTermYears = 1,
                            Name = "Auto Protect",
                            RequiredDocuments = "[\"RC Book\",\"Driving License\"]"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            AdminFee = 100m,
                            BasePremiumRate = 1.0m,
                            Category = "Home",
                            CreatedAt = new DateTime(2026, 3, 28, 6, 24, 3, 728, DateTimeKind.Utc).AddTicks(2742),
                            Description = "Protect your home against fire, theft, and natural calamities",
                            EligibilityCriteria = "",
                            Features = "[\"Building Cover\",\"Contents Cover\",\"Natural Calamities\"]",
                            IsActive = true,
                            IsDeleted = false,
                            MaxCoverageAmount = 10000000m,
                            MaxTermYears = 10,
                            MinCoverageAmount = 500000m,
                            MinTermYears = 1,
                            Name = "Home Shield",
                            RequiredDocuments = "[\"Property Proof\",\"Valuation Report\"]"
                        });
                });

            modelBuilder.Entity("PolicyService.Models.Policy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActivationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BeneficiaryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BeneficiaryRelationship")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CancellationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CancellationReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("CoverageAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("NomineeDetails")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentFrequency")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("TermYears")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalPremium")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PolicyNumber")
                        .IsUnique();

                    b.HasIndex("ProductId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("Policies");
                });

            modelBuilder.Entity("PolicyService.Models.PolicyDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DocumentName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("DocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("DocumentUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UploadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VerifiedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PolicyId");

                    b.ToTable("PolicyDocuments");
                });

            modelBuilder.Entity("PolicyService.Models.PremiumPayment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("InstallmentNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsGracePeriod")
                        .HasColumnType("bit");

                    b.Property<decimal>("LateFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("PaidDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentStatus")
                        .HasColumnType("int");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PaymentStatus");

                    b.HasIndex("PolicyId");

                    b.ToTable("Premiums");
                });

            modelBuilder.Entity("PolicyService.Models.Policy", b =>
                {
                    b.HasOne("PolicyService.Models.InsuranceProduct", "Product")
                        .WithMany("Policies")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("PolicyService.Models.PolicyDocument", b =>
                {
                    b.HasOne("PolicyService.Models.Policy", "Policy")
                        .WithMany("Documents")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("PolicyService.Models.PremiumPayment", b =>
                {
                    b.HasOne("PolicyService.Models.Policy", "Policy")
                        .WithMany("Premiums")
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Policy");
                });

            modelBuilder.Entity("PolicyService.Models.InsuranceProduct", b =>
                {
                    b.Navigation("Policies");
                });

            modelBuilder.Entity("PolicyService.Models.Policy", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("Premiums");
                });
#pragma warning restore 612, 618
        }
    }
}
