using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace SmartSure.AdminService.Services
{
    /// <summary>
    /// Represent or implements PdfGeneratorService.
    /// </summary>
    public class PdfGeneratorService : IPdfGeneratorService
    {
        public PdfGeneratorService()
        {
            // Set QuestPDF license (Community license is free for open source)
            QuestPDF.Settings.License = LicenseType.Community;
        }

        /// <summary>
        /// Performs the GenerateSalesReportPdf operation.
        /// </summary>
        public byte[] GenerateSalesReportPdf(SalesReportData data)
        {
            return Document.Create(container =>
            {
                container.Page(page =>
                {
                    page.Size(PageSizes.A4);
                    page.Margin(40);
                    page.PageColor(Colors.White);
                    page.DefaultTextStyle(x => x.FontSize(11).FontFamily("Arial"));

                    page.Header().Element(header => ComposeHeader(header, data));
                    page.Content().Element(content => ComposeContent(content, data));
                    page.Footer().Element(ComposeFooter);
                });
            }).GeneratePdf();
        }

        private void ComposeHeader(IContainer container, SalesReportData data)
        {
            var logoSvg = @"<svg viewBox=""0 0 32 32"" fill=""none"">
                <path d=""M16 0L32 8V24L16 32L0 24V8L16 0Z"" fill=""#1A1A1A""/>
                <path d=""M16 5V27L4 21V11L16 5Z"" fill=""#0DB18C""/>
                <path d=""M16 5L28 11V21L16 27V5Z"" fill=""#0A8E70""/>
            </svg>";

            container.Row(row =>
            {
                row.ConstantItem(45).Height(45).Svg(logoSvg);
                row.ConstantItem(15); // Gap

                row.RelativeItem().Column(column =>
                {
                    column.Item().Text(text =>
                    {
                        text.Span("SMART").FontSize(24).ExtraBold().FontColor("#1A1A1A");
                        text.Span("SURE").FontSize(24).ExtraBold().FontColor("#0DB18C");
                    });

                    column.Item().Text($"{data.ReportType} Report")
                        .FontSize(14)
                        .FontColor("#0DB18C"); // Highlighting report type in brand teal
                });
            });
        }

        private void ComposeContent(IContainer container, SalesReportData data)
        {
            container.PaddingVertical(20).Column(column =>
            {
                column.Spacing(15);

                // Report Info Section
                column.Item().Element(c => ComposeReportInfo(c, data));

                // Conditional Subsections based on Scope Type
                var type = data.ReportType?.ToLower() ?? "";

                if (type.Contains("claims"))
                {
                    column.Item().Element(c => ComposeClaimsAnalysis(c, data));
                    if (data.MonthlyTrends.Any())
                        column.Item().Element(c => ComposeMonthlyTrends(c, data));
                }
                else if (type.Contains("operational"))
                {
                    column.Item().Element(c => ComposeKeyMetrics(c, data));
                    if (data.PolicyBreakdown.Any())
                        column.Item().Element(c => ComposePolicyBreakdown(c, data));
                }
                else // Default to Financial Metrics or "All"
                {
                    column.Item().Element(c => ComposeKeyMetrics(c, data));
                    
                    if (data.PolicyBreakdown.Any())
                        column.Item().Element(c => ComposePolicyBreakdown(c, data));
                    
                    if (data.MonthlyTrends.Any())
                        column.Item().Element(c => ComposeMonthlyTrends(c, data));
                }
            });
        }

        private void ComposeReportInfo(IContainer container, SalesReportData data)
        {
            container.Background("#F8FAFC").Padding(15).Column(column =>
            {
                column.Spacing(5);

                column.Item().Row(row =>
                {
                    row.RelativeItem().Text($"Report Period: {data.DateRangeStart:MMM dd, yyyy} - {data.DateRangeEnd:MMM dd, yyyy}")
                        .FontSize(12).SemiBold();
                });

                column.Item().Text($"Generated: {DateTime.Now:MMM dd, yyyy HH:mm}")
                    .FontSize(10).FontColor("#666666");

                column.Item().Text($"Generated By: {data.GeneratedBy}")
                    .FontSize(10).FontColor("#666666");
            });
        }

        private void ComposeKeyMetrics(IContainer container, SalesReportData data)
        {
            container.Column(column =>
            {
                column.Item().PaddingBottom(10).Text("Key Performance Metrics")
                    .FontSize(16).Bold().FontColor("#1A1A1A");

                column.Item().Row(row =>
                {
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Total Policies Sold", data.TotalPoliciesSold.ToString(), "#0DB18C"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Total Users", data.TotalUsers.ToString(), "#3B82F6"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Claims Received", data.TotalClaimsReceived.ToString(), "#F59E0B"));
                });

                column.Item().PaddingTop(10).Row(row =>
                {
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Total Revenue", $"₹{data.TotalRevenue:N0}", "#10B981"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Claims Paid", $"₹{data.TotalClaimsPaid:N0}", "#EF4444"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeMetricCard(c, "Net Profit", $"₹{(data.TotalRevenue - data.TotalClaimsPaid):N0}", "#8B5CF6"));
                });
            });
        }

        private void ComposeMetricCard(IContainer container, string label, string value, string color)
        {
            container.Border(1).BorderColor("#E5E7EB").Background("#FFFFFF").Padding(12).Column(column =>
            {
                column.Item().Text(label).FontSize(10).FontColor("#666666");
                column.Item().PaddingTop(5).Text(value).FontSize(18).Bold().FontColor(color);
            });
        }

        private void ComposePolicyBreakdown(IContainer container, SalesReportData data)
        {
            container.Column(column =>
            {
                column.Item().PaddingTop(10).PaddingBottom(10).Text("Policy Type Breakdown")
                    .FontSize(16).Bold().FontColor("#1A1A1A");

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(3);
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                    });

                    // Header
                    table.Header(header =>
                    {
                        header.Cell().Background("#0DB18C").Padding(8).Text("Policy Type").FontColor(Colors.White).Bold();
                        header.Cell().Background("#0DB18C").Padding(8).Text("Count").FontColor(Colors.White).Bold();
                        header.Cell().Background("#0DB18C").Padding(8).Text("Revenue").FontColor(Colors.White).Bold();
                        header.Cell().Background("#0DB18C").Padding(8).Text("% of Total").FontColor(Colors.White).Bold();
                    });

                    // Rows
                    foreach (var item in data.PolicyBreakdown)
                    {
                        var percentage = data.TotalPoliciesSold > 0 ? (item.Count * 100.0 / data.TotalPoliciesSold) : 0;

                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text(item.TypeName);
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text(item.Count.ToString());
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text($"₹{item.Revenue:N0}");
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text($"{percentage:F1}%");
                    }
                });
            });
        }

        private void ComposeMonthlyTrends(IContainer container, SalesReportData data)
        {
            container.Column(column =>
            {
                column.Item().PaddingTop(10).PaddingBottom(10).Text("Monthly Trends")
                    .FontSize(16).Bold().FontColor("#1A1A1A");

                column.Item().Table(table =>
                {
                    table.ColumnsDefinition(columns =>
                    {
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                        columns.RelativeColumn(2);
                    });

                    // Header
                    table.Header(header =>
                    {
                        header.Cell().Background("#3B82F6").Padding(8).Text("Month").FontColor(Colors.White).Bold();
                        header.Cell().Background("#3B82F6").Padding(8).Text("Policies Sold").FontColor(Colors.White).Bold();
                        header.Cell().Background("#3B82F6").Padding(8).Text("Claims").FontColor(Colors.White).Bold();
                        header.Cell().Background("#3B82F6").Padding(8).Text("Revenue").FontColor(Colors.White).Bold();
                    });

                    // Rows
                    foreach (var trend in data.MonthlyTrends)
                    {
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text(trend.Month);
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text(trend.PoliciesSold.ToString());
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text(trend.ClaimsReceived.ToString());
                        table.Cell().Border(1).BorderColor("#E5E7EB").Padding(8).Text($"₹{trend.Revenue:N0}");
                    }
                });
            });
        }

        private void ComposeClaimsAnalysis(IContainer container, SalesReportData data)
        {
            container.Column(column =>
            {
                column.Item().PaddingTop(10).PaddingBottom(10).Text("Claims Analysis")
                    .FontSize(16).Bold().FontColor("#1A1A1A");

                column.Item().Row(row =>
                {
                    row.RelativeItem().Element(c => ComposeClaimStatusCard(c, "Approved", data.TotalClaimsApproved, "#10B981"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeClaimStatusCard(c, "Rejected", data.TotalClaimsRejected, "#EF4444"));
                    row.Spacing(10);
                    row.RelativeItem().Element(c => ComposeClaimStatusCard(c, "Pending", data.TotalClaimsPending, "#F59E0B"));
                });

                if (data.TotalClaimsReceived > 0)
                {
                    var approvalRate = (data.TotalClaimsApproved * 100.0 / data.TotalClaimsReceived);
                    column.Item().PaddingTop(10).Background("#F0FDF4").Padding(12).Text($"Claim Approval Rate: {approvalRate:F1}%")
                        .FontSize(12).Bold().FontColor("#10B981");
                }
            });
        }

        private void ComposeClaimStatusCard(IContainer container, string status, int count, string color)
        {
            container.Border(1).BorderColor("#E5E7EB").Padding(12).Column(column =>
            {
                column.Item().Text(status).FontSize(11).FontColor("#666666");
                column.Item().PaddingTop(5).Text(count.ToString()).FontSize(20).Bold().FontColor(color);
            });
        }

        private void ComposeFooter(IContainer container)
        {
            container.AlignCenter().Text(text =>
            {
                text.Span("SmartSure Insurance Management System | ").FontSize(9).FontColor("#999999");
                text.Span("Confidential Report").FontSize(9).FontColor("#999999").Italic();
            });
        }
    }
}
