using System.Net.Http.Json;
using SmartSure.AdminService.DTOs;
using SmartSure.AdminService.Models;
using SmartSure.AdminService.Repositories;
using System.Text.Json;

namespace SmartSure.AdminService.Services
{
    /// <summary>
    /// Represent or implements ReportService.
    /// </summary>
    public class ReportService : IReportService
    {
        private readonly IReportRepository _repository;
        private readonly ILogger<ReportService> _logger;
        private readonly IHttpClientFactory _httpClientFactory;
        private readonly IConfiguration _configuration;
        private readonly IPdfGeneratorService _pdfGenerator;

        public ReportService(
            IReportRepository repository, 
            ILogger<ReportService> logger, 
            IHttpClientFactory httpClientFactory, 
            IConfiguration configuration,
            IPdfGeneratorService pdfGenerator)
        {
            _repository = repository;
            _logger = logger;
            _httpClientFactory = httpClientFactory;
            _configuration = configuration;
            _pdfGenerator = pdfGenerator;
        }

        /// <summary>
        /// Performs the GeneratePdfReportAsync operation.
        /// </summary>
        public async Task<byte[]> GeneratePdfReportAsync(Guid adminId, ReportRequestDTO dto, string token)
        {
            var reportData = await CollectReportDataAsync(dto, token);
            
            // Get admin name
            var adminName = await GetAdminNameAsync(adminId, token);
            reportData.GeneratedBy = adminName;
            
            var pdfBytes = _pdfGenerator.GenerateSalesReportPdf(reportData);
            
            // Save report metadata to database
            var report = new Report
            {
                ReportId = Guid.NewGuid(),
                Title = dto.Title,
                ReportType = dto.ReportType,
                Format = "PDF",
                Content = Convert.ToBase64String(pdfBytes),
                GeneratedBy = adminId,
                DateRangeStart = dto.DateRangeStart,
                DateRangeEnd = dto.DateRangeEnd
            };

            await _repository.AddAsync(report);
            await _repository.SaveChangesAsync();

            _logger.LogInformation("PDF Report {ReportId} generated by admin {AdminId}", report.ReportId, adminId);

            return pdfBytes;
        }

        public async Task<byte[]> RegeneratePdfAsync(Guid reportId, string token)
        {
            var report = await _repository.GetByIdAsync(reportId);
            if (report == null) return Array.Empty<byte>();

            var dto = new ReportRequestDTO
            {
                Title = report.Title,
                ReportType = report.ReportType,
                DateRangeStart = report.DateRangeStart,
                DateRangeEnd = report.DateRangeEnd,
                Format = "PDF"
            };

            var reportData = await CollectReportDataAsync(dto, token);
            var adminName = await GetAdminNameAsync(report.GeneratedBy, token);
            reportData.GeneratedBy = adminName;
            
            return _pdfGenerator.GenerateSalesReportPdf(reportData);
        }

        private async Task<SalesReportData> CollectReportDataAsync(ReportRequestDTO dto, string token)
        {
            var gatewayUrl = _configuration["Gateway:Url"] ?? "http://localhost:5057";
            var client = _httpClientFactory.CreateClient();
            
            var cleanToken = token.Replace("Bearer ", "").Trim();
            client.DefaultRequestHeaders.Add("Authorization", $"Bearer {cleanToken}");

            var reportData = new SalesReportData
            {
                ReportType = dto.ReportType,
                DateRangeStart = dto.DateRangeStart,
                DateRangeEnd = dto.DateRangeEnd
            };

            try
            {
                // Fetch all policies
                var policiesResponse = await client.GetAsync($"{gatewayUrl}/policies/all");
                List<JsonElement> allPolicies = new();
                
                if (policiesResponse.IsSuccessStatusCode)
                {
                    var policiesStr = await policiesResponse.Content.ReadAsStringAsync();
                    using var doc = JsonDocument.Parse(policiesStr);
                    if (doc.RootElement.ValueKind == JsonValueKind.Array)
                    {
                        allPolicies = doc.RootElement.EnumerateArray().Select(e => e.Clone()).ToList();
                    }
                    else if (doc.RootElement.ValueKind == JsonValueKind.Object && 
                             doc.RootElement.TryGetProperty("$values", out var vals) && 
                             vals.ValueKind == JsonValueKind.Array)
                    {
                        allPolicies = vals.EnumerateArray().Select(e => e.Clone()).ToList();
                    }
                }

                // Filter policies by date range
                var filteredPolicies = allPolicies.Where(p =>
                {
                    if (p.TryGetProperty("createdAt", out var createdAt) || p.TryGetProperty("CreatedAt", out createdAt))
                    {
                        if (DateTime.TryParse(createdAt.GetString(), out var date))
                        {
                            return date >= dto.DateRangeStart && date <= dto.DateRangeEnd;
                        }
                    }
                    return false;
                }).ToList();

                reportData.TotalPoliciesSold = filteredPolicies.Count;

                // Calculate total revenue
                reportData.TotalRevenue = filteredPolicies.Sum(p =>
                {
                    if (p.TryGetProperty("premiumAmount", out var premium) || p.TryGetProperty("PremiumAmount", out premium))
                    {
                        if (premium.ValueKind == JsonValueKind.Number)
                        {
                            return premium.GetDecimal();
                        }
                    }
                    return 0m;
                });

                // Policy breakdown by type
                var policyGroups = filteredPolicies.GroupBy(p =>
                {
                    if (p.TryGetProperty("typeName", out var typeName) || p.TryGetProperty("TypeName", out typeName))
                    {
                        return typeName.GetString() ?? "Unknown";
                    }
                    return "Unknown";
                });

                foreach (var group in policyGroups)
                {
                    var revenue = group.Sum(p =>
                    {
                        if (p.TryGetProperty("premiumAmount", out var premium) || p.TryGetProperty("PremiumAmount", out premium))
                        {
                            if (premium.ValueKind == JsonValueKind.Number)
                            {
                                return premium.GetDecimal();
                            }
                        }
                        return 0m;
                    });

                    reportData.PolicyBreakdown.Add(new PolicyTypeBreakdown
                    {
                        TypeName = group.Key,
                        Count = group.Count(),
                        Revenue = revenue
                    });
                }

                // Monthly trends
                var monthlyGroups = filteredPolicies.GroupBy(p =>
                {
                    if (p.TryGetProperty("createdAt", out var createdAt) || p.TryGetProperty("CreatedAt", out createdAt))
                    {
                        if (DateTime.TryParse(createdAt.GetString(), out var date))
                        {
                            return date.ToString("MMM yyyy");
                        }
                    }
                    return "Unknown";
                });

                foreach (var group in monthlyGroups.OrderBy(g => g.Key))
                {
                    var revenue = group.Sum(p =>
                    {
                        if (p.TryGetProperty("premiumAmount", out var premium) || p.TryGetProperty("PremiumAmount", out premium))
                        {
                            if (premium.ValueKind == JsonValueKind.Number)
                            {
                                return premium.GetDecimal();
                            }
                        }
                        return 0m;
                    });

                    reportData.MonthlyTrends.Add(new MonthlyTrend
                    {
                        Month = group.Key,
                        PoliciesSold = group.Count(),
                        Revenue = revenue,
                        ClaimsReceived = 0 // Will be filled from claims data
                    });
                }

                // Fetch all claims
                var claimsResponse = await client.GetAsync($"{gatewayUrl}/claims/all");
                List<JsonElement> allClaims = new();
                
                if (claimsResponse.IsSuccessStatusCode)
                {
                    var claimsStr = await claimsResponse.Content.ReadAsStringAsync();
                    using var doc = JsonDocument.Parse(claimsStr);
                    if (doc.RootElement.ValueKind == JsonValueKind.Array)
                    {
                        allClaims = doc.RootElement.EnumerateArray().Select(e => e.Clone()).ToList();
                    }
                    else if (doc.RootElement.ValueKind == JsonValueKind.Object && 
                             doc.RootElement.TryGetProperty("$values", out var vals) && 
                             vals.ValueKind == JsonValueKind.Array)
                    {
                        allClaims = vals.EnumerateArray().Select(e => e.Clone()).ToList();
                    }
                }

                // Filter claims by date range
                var filteredClaims = allClaims.Where(c =>
                {
                    if (c.TryGetProperty("createdAt", out var createdAt) || c.TryGetProperty("CreatedAt", out createdAt))
                    {
                        if (DateTime.TryParse(createdAt.GetString(), out var date))
                        {
                            return date >= dto.DateRangeStart && date <= dto.DateRangeEnd;
                        }
                    }
                    return false;
                }).ToList();

                reportData.TotalClaimsReceived = filteredClaims.Count;
                reportData.TotalClaimsApproved = filteredClaims.Count(c =>
                {
                    if (c.TryGetProperty("status", out var status) || c.TryGetProperty("Status", out status))
                    {
                        return status.GetString() == "Approved";
                    }
                    return false;
                });
                reportData.TotalClaimsRejected = filteredClaims.Count(c =>
                {
                    if (c.TryGetProperty("status", out var status) || c.TryGetProperty("Status", out status))
                    {
                        return status.GetString() == "Rejected";
                    }
                    return false;
                });
                reportData.TotalClaimsPending = filteredClaims.Count(c =>
                {
                    if (c.TryGetProperty("status", out var status) || c.TryGetProperty("Status", out status))
                    {
                        var s = status.GetString();
                        return s != "Approved" && s != "Rejected";
                    }
                    return false;
                });

                // Calculate total claims paid
                reportData.TotalClaimsPaid = filteredClaims.Where(c =>
                {
                    if (c.TryGetProperty("status", out var status) || c.TryGetProperty("Status", out status))
                    {
                        return status.GetString() == "Approved";
                    }
                    return false;
                }).Sum(c =>
                {
                    if (c.TryGetProperty("claimAmount", out var amount) || c.TryGetProperty("ClaimAmount", out amount))
                    {
                        if (amount.ValueKind == JsonValueKind.Number)
                        {
                            return amount.GetDecimal();
                        }
                    }
                    return 0m;
                });

                // Update monthly trends with claims data
                var claimsByMonth = filteredClaims.GroupBy(c =>
                {
                    if (c.TryGetProperty("createdAt", out var createdAt) || c.TryGetProperty("CreatedAt", out createdAt))
                    {
                        if (DateTime.TryParse(createdAt.GetString(), out var date))
                        {
                            return date.ToString("MMM yyyy");
                        }
                    }
                    return "Unknown";
                });

                foreach (var group in claimsByMonth)
                {
                    var trend = reportData.MonthlyTrends.FirstOrDefault(t => t.Month == group.Key);
                    if (trend != null)
                    {
                        trend.ClaimsReceived = group.Count();
                    }
                }

                // Fetch total users
                var usersResponse = await client.GetAsync($"{gatewayUrl}/auth/users");
                if (usersResponse.IsSuccessStatusCode)
                {
                    var usersStr = await usersResponse.Content.ReadAsStringAsync();
                    using var doc = JsonDocument.Parse(usersStr);
                    if (doc.RootElement.ValueKind == JsonValueKind.Array)
                    {
                        reportData.TotalUsers = doc.RootElement.GetArrayLength();
                    }
                    else if (doc.RootElement.ValueKind == JsonValueKind.Object && 
                             doc.RootElement.TryGetProperty("$values", out var vals) && 
                             vals.ValueKind == JsonValueKind.Array)
                    {
                        reportData.TotalUsers = vals.GetArrayLength();
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error collecting report data");
                throw;
            }

            return reportData;
        }

        private async Task<string> GetAdminNameAsync(Guid adminId, string token)
        {
            try
            {
                var gatewayUrl = _configuration["Gateway:Url"] ?? "http://localhost:5057";
                var client = _httpClientFactory.CreateClient();
                
                var cleanToken = token.Replace("Bearer ", "").Trim();
                client.DefaultRequestHeaders.Add("Authorization", $"Bearer {cleanToken}");

                var response = await client.GetAsync($"{gatewayUrl}/auth/me");
                if (response.IsSuccessStatusCode)
                {
                    var userStr = await response.Content.ReadAsStringAsync();
                    var user = JsonSerializer.Deserialize<JsonElement>(userStr);
                    if (user.TryGetProperty("fullName", out var fullName) || user.TryGetProperty("FullName", out fullName))
                    {
                        return fullName.GetString() ?? "Admin";
                    }
                }
            }
            catch (Exception ex)
            {
                _logger.LogWarning(ex, "Could not fetch admin name");
            }

            return "Admin";
        }

        /// <summary>
        /// Performs the GenerateReportAsync operation.
        /// </summary>
        public async Task<ReportResponseDTO> GenerateReportAsync(Guid adminId, ReportRequestDTO dto, string token)
        {
            var content = await GenerateContentAsync(dto, token);

            var report = new Report
            {
                ReportId = Guid.NewGuid(),
                Title = dto.Title,
                ReportType = dto.ReportType,
                Format = dto.Format,
                Content = content,
                GeneratedBy = adminId,
                DateRangeStart = dto.DateRangeStart,
                DateRangeEnd = dto.DateRangeEnd
            };

            await _repository.AddAsync(report);
            await _repository.SaveChangesAsync();

            _logger.LogInformation("Report {ReportId} generated by admin {AdminId}: {Title}", report.ReportId, adminId, dto.Title);

            return MapToDto(report);
        }

        /// <summary>
        /// Performs the GetReportsAsync operation.
        /// </summary>
        public async Task<List<ReportResponseDTO>> GetReportsAsync()
        {
            var reports = await _repository.GetAllAsync();
            return reports.Select(MapToDto).ToList();
        }

        /// <summary>
        /// Performs the GetReportByIdAsync operation.
        /// </summary>
        public async Task<ReportResponseDTO?> GetReportByIdAsync(Guid reportId)
        {
            var report = await _repository.GetByIdAsync(reportId);
            return report == null ? null : MapToDto(report);
        }

        private async Task<string> GenerateContentAsync(ReportRequestDTO dto, string token)
        {
            var reportData = await CollectReportDataAsync(dto, token);

            var reportContent = new
            {
                title = dto.Title,
                type = dto.ReportType,
                dateRange = new { start = dto.DateRangeStart, end = dto.DateRangeEnd },
                generatedAt = DateTime.UtcNow,
                summary = $"Report generated for {dto.ReportType} from {dto.DateRangeStart:yyyy-MM-dd} to {dto.DateRangeEnd:yyyy-MM-dd}",
                statistics = new
                {
                    totalPoliciesSold = reportData.TotalPoliciesSold,
                    totalUsers = reportData.TotalUsers,
                    totalClaimsReceived = reportData.TotalClaimsReceived,
                    totalClaimsApproved = reportData.TotalClaimsApproved,
                    totalClaimsRejected = reportData.TotalClaimsRejected,
                    totalClaimsPending = reportData.TotalClaimsPending,
                    totalRevenue = reportData.TotalRevenue,
                    totalClaimsPaid = reportData.TotalClaimsPaid,
                    netProfit = reportData.TotalRevenue - reportData.TotalClaimsPaid
                },
                policyBreakdown = reportData.PolicyBreakdown,
                monthlyTrends = reportData.MonthlyTrends
            };

            return JsonSerializer.Serialize(reportContent);
        }

        private static ReportResponseDTO MapToDto(Report report)
        {
            return new ReportResponseDTO
            {
                ReportId = report.ReportId,
                Title = report.Title,
                ReportType = report.ReportType,
                Format = report.Format,
                Content = report.Content,
                GeneratedBy = report.GeneratedBy,
                DateRangeStart = report.DateRangeStart,
                DateRangeEnd = report.DateRangeEnd,
                CreatedAt = report.CreatedAt
            };
        }

        /// <summary>
        /// Performs the DeleteReportAsync operation.
        /// </summary>
        public async Task<bool> DeleteReportAsync(Guid reportId)
        {
            var report = await _repository.GetByIdAsync(reportId);
            if (report == null)
            {
                return false;
            }

            await _repository.DeleteAsync(report);
            return true;
        }
    }
}
